service: strapi-4-serverless-guide

frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1 # NOTE: Update to your region
  logRetentionInDays: 1
  versionFunctions: false
  deploymentBucket:
    name: ruuby-test-deployment

  vpc:
    securityGroupIds:
      - sg-4916f333
      - sg-f3c7dc88
      - sg-26cad15d
    subnetIds:
      - subnet-08cb2640
      - subnet-ac93c9f7

  memorySize: 2048
  timeout: 15

  environment:
    APP_KEYS: ${env:APP_KEYS}
    API_TOKEN_SALT: ${env:API_TOKEN_SALT}
    ADMIN_JWT_SECRET: ${env:ADMIN_JWT_SECRET}
    JWT_SECRET: ${env:JWT_SECRET}

    SERVER_URL: ${env:SERVER_URL}
    DATABASE_PASSWORD: ${env:DATABASE_PASSWORD}
    DATABASE_USERNAME: ${env:DATABASE_USERNAME}
    DATABASE_NAME: ${env:DATABASE_NAME}
    DATABASE_HOST: ${env:DATABASE_HOST}
    DATABASE_PORT: ${env:DATABASE_PORT}

package:
  patterns:
    - package.json
    - src/resources/
    - public
    - build
    - config
    - database

functions:
  api:
    handler: src/app.strapiHandler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
  - serverless-esbuild

custom:
  esbuild:
    external:
      - mysql
      - mysql2
      - oracledb
      - pg-query-stream
      - sqlite3
      - tedious
      - sequelize
      - redis
      - mongoose
      - "@strapi/plugin-content-manager"
      - "@strapi/plugin-content-type-builder"
      - "@strapi/plugin-email"
      - "@strapi/plugin-upload"